# Generated by Django 4.0.4 on 2023-03-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pincode',
            field=models.CharField(max_length=60),
        ),
    ]
